ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'production'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'rails'
require 'rubygems'
require 'httparty'

require 'csv'

sites = %w{
bitbucket.support-backup.beiersdorf.com
px1-sa.vx.beiersdorf.com
lync09ws.beiersdorf.com
confluence.support-backup.beiersdorf.com
api-acios.beiersdorf.com
ebm.beiersdorf.com
mam-q.beiersdorf.com
jira.support-test.beiersdorf.com
internal-eshop.beiersdorf.com
mam.beiersdorf.com
az-vpn.beiersdorf.com
webmail.support.beiersdorf.com
lync13ws.beiersdorf.com
lync06ws.beiersdorf.com
wwwde.beiersdorf.com
azext-eu-u22.beiersdorf.com
sbc01.beiersdorf.com
cms10test.beiersdorf.com
view.n.beiersdorf.com
micro-cd-eu-1-prod.beiersdorf.com
mail1.beiersdorf.com
ag.beiersdorf.com
login-www-skin-stories-com.beiersdorf.com
medical.beiersdorf.com
mediaxtrack.beiersdorf.com
az-temp-win-frontend.beiersdorf.com
tm-eu.beiersdorf.com
annualreport2019.beiersdorf.com
www.annualreport2006.beiersdorf.com
cms10test-cd.beiersdorf.com
www.interimreport2018-q2.beiersdorf.com
t.beiersdorf.com
mbluenet-de.beiersdorf.com
qa-micro-designmanual.beiersdorf.com
m.beiersdorf.com
www.interimreport-old.beiersdorf.com
adb2creverse.beiersdorf.com
maintenancepage.beiersdorf.com
www.m.beiersdorf.com
qa-pressportal-no.beiersdorf.com
niveadesign.beiersdorf.com
www.nhc.beiersdorf.com
www.annualreport2008.beiersdorf.com
support-backup.beiersdorf.com
internal-eshop-stage.beiersdorf.com
av02.beiersdorf.com
skin-study.beiersdorf.com
meet.beiersdorf.com
jira.support-u22.beiersdorf.com
pharmacy.beiersdorf.com
vx.beiersdorf.com
soc.beiersdorf.com
compass.beiersdorf.com
countrymaster.beiersdorf.com
hello.beiersdorf.com
acios.beiersdorf.com
payment.beiersdorf.com
interimreport2015-q3.beiersdorf.com
interimreport-old.beiersdorf.com
almers.beiersdorf.com
az-temp-lx-frontend.beiersdorf.com
c.emails.beiersdorf.com
www.futuro.beiersdorf.com
extsetup.beiersdorf.com
essentials.beiersdorf.com
jenkins.beiersdorf.com
futuro.beiersdorf.com
scm-newsletter.beiersdorf.com
azext-kompass-u22.beiersdorf.com
maintenance.beiersdorf.com
cms.prelive.beiersdorf.com
rooms.beiersdorf.com
cms-qa-microsites.beiersdorf.com
www.systemmails.beiersdorf.com
www.rooms.beiersdorf.com
internal-eshop-dev.beiersdorf.com
mail.systemmails.beiersdorf.com
mobile.beiersdorf.com
annualreport2010.beiersdorf.com
api.swagger-qual.beiersdorf.com
annualreport2009.beiersdorf.com
rinku.zaq.ne.akarta.beiersdorf.com
uat-es-mx.beiersdorf.com
uat-fr-ch.beiersdorf.com
hallo.beiersdorf.com
career.beiersdorf.com
eordering.beiersdorf.com
cwa.beiersdorf.com
ad-gallery.beiersdorf.com
www.interimreport.beiersdorf.com
a.beiersdorf.com
mi.beiersdorf.com
chat.beiersdorf.com
www.interimreport2015-q3.beiersdorf.com
pressportal-se.beiersdorf.com
annualreport2011.beiersdorf.com
bpm.beiersdorf.com
image.n.beiersdorf.com
tm-eu-test.beiersdorf.com
test.beiersdorf.com
qa-micro-pressportal-at.beiersdorf.com
micro-pos-excellence-prelive.beiersdorf.com
mam-fnc-d.beiersdorf.com
www.acc.biophysics.beiersdorf.com
jira.support-test-pg.beiersdorf.com
dam-q-api.beiersdorf.com
messenger.beiersdorf.com
404errorpage.beiersdorf.com
adb2clogin.beiersdorf.com
socialwall-prelive.beiersdorf.com
terminal-test.beiersdorf.com
connect.beiersdorf.com
micro-nivea-essentials-prelive.beiersdorf.com
intouch.beiersdorf.com
direc01ws.beiersdorf.com
av03.beiersdorf.com
support-t.beiersdorf.com
pos-excellence.beiersdorf.com
annualreport2006.beiersdorf.com
trademarketing.beiersdorf.com
22essentials.beiersdorf.com
userguide-labello-qa.beiersdorf.com
w3.beiersdorf.com
dam-storagehandler-api.beiersdorf.com
shop-stag.beiersdorf.com
lync12ws.beiersdorf.com
vintage.beiersdorf.com
trusted-pearlfinder.beiersdorf.com
az-support.beiersdorf.com
mta.n.beiersdorf.com
press.beiersdorf.com
autodiscover.beiersdorf.com
uat-de-ch.beiersdorf.com
azext-eu-win.beiersdorf.com
www1.beiersdorf.com
dam-uaa.beiersdorf.com
xfl.alnere.beiersdorf.com
assets.beiersdorf.com
alnere.beiersdorf.com
www.annualreport2010.beiersdorf.com
bitbucket.az-support.beiersdorf.com
www.annualreport2013.beiersdorf.com
payment-uat.beiersdorf.com
qa-microsites.beiersdorf.com
azext-ruexperts.beiersdorf.com
oscar-and-paul-battleweeks.beiersdorf.com
cms16-14socialwall.beiersdorf.com
azext-devops-backup-u22.beiersdorf.com
annualreport2017.beiersdorf.com
www.ncr.beiersdorf.com
news.beiersdorf.com
adelaide.beiersdorf.com
pre-mediaxtrack.beiersdorf.com
eucerin.beiersdorf.com
px1-me.vx.beiersdorf.com
qa-mam-userguide.beiersdorf.com
acc.biophysics.beiersdorf.com
cms10.beiersdorf.com
a.emails.beiersdorf.com
presseportal-se.beiersdorf.com
ncr.beiersdorf.com
www.interimreport2014-q3.beiersdorf.com
t.emails.beiersdorf.com
micro-demo.beiersdorf.com
interimreport2015-q1.beiersdorf.com
styleguide.beiersdorf.com
sonar.beiersdorf.com
confluence.support.beiersdorf.com
mail2.beiersdorf.com
www.sustainability.beiersdorf.com
image.medical.beiersdorf.com
click.n.beiersdorf.com
nhd.beiersdorf.com
ssl.beiersdorf.com
care-os.beiersdorf.com
bluestream.beiersdorf.com
px2-eu.vx.beiersdorf.com
support-q.beiersdorf.com
qa-micro-pos-excellence.beiersdorf.com
cargo.beiersdorf.com
sf-dev.beiersdorf.com
expressway.cisco.beiersdorf.com
ucpool05ws.beiersdorf.com
interimreport.beiersdorf.com
az-ci-frontdoor.beiersdorf.com
sip.beiersdorf.com
sbcusa01.beiersdorf.com
azext-op.beiersdorf.com
www.annualreport2005.beiersdorf.com
admin.acios.beiersdorf.com
lync04ws.beiersdorf.com
lyncdiscover.beiersdorf.com
bdflp2.beiersdorf.com
socialwall.beiersdorf.com
qa-beiersdorf-dermo-medical.beiersdorf.com
www.beiersdorf.com
www.phc.beiersdorf.com
annualreport2008.beiersdorf.com
dam-q-storagehandler-api.beiersdorf.com
www.bss.beiersdorf.com
lync05ws.beiersdorf.com
ucpool08ws.beiersdorf.com
azext-kompass.beiersdorf.com
terminal-shopfloor.beiersdorf.com
terminal.beiersdorf.com
px-eu.vx.beiersdorf.com
cms-socialwall-prelive.beiersdorf.com
confluence.az-support.beiersdorf.com
interimreport2017-q2.beiersdorf.com
jira.az-support.beiersdorf.com
webconf03.beiersdorf.com
qa-pressportal-fi.beiersdorf.com
ucpool10ws.beiersdorf.com
bdflp1.beiersdorf.com
microscopy.beiersdorf.com
nlc.beiersdorf.com
marketplace-prelive.beiersdorf.com
training.beiersdorf.com
dam-userguide.beiersdorf.com
micro-userguide-prelive.beiersdorf.com
reports.beiersdorf.com
qa-pressportal-se.beiersdorf.com
www.interimreport2014-q1.beiersdorf.com
cms10uat.beiersdorf.com
micro-cd-eu-2-prod.beiersdorf.com
mta.medical.beiersdorf.com
link.beiersdorf.com
sbcbra01.beiersdorf.com
www.prp.beiersdorf.com
qa-micro-nivea-essentials.beiersdorf.com
cms-socialwall.beiersdorf.com
8x4-pimexport.beiersdorf.com
lync08ws.beiersdorf.com
preview.beiersdorf.com
www.annualreport2014.beiersdorf.com
v.beiersdorf.com
lync10ws.beiersdorf.com
ee.beiersdorf.com
prp.beiersdorf.com
zbericht.beiersdorf.com
n.beiersdorf.com
ca.beiersdorf.com
azext-us.beiersdorf.com
www.interimreport2015-q1.beiersdorf.com
support-test.beiersdorf.com
prelive.beiersdorf.com
www.annualreport2017.beiersdorf.com
az-temp-win-backend.beiersdorf.com
pim1-userguide.beiersdorf.com
www.nhd.beiersdorf.com
qa-pressportal-dk.beiersdorf.com
img.beiersdorf.com
tsgw-shopfloor.beiersdorf.com
showroom.beiersdorf.com
jira.support-backup.beiersdorf.com
lync14ws.beiersdorf.com
mbluenet.beiersdorf.com
designmanual.beiersdorf.com
room.beiersdorf.com
22tsgw.beiersdorf.com
azext-devops-u22.beiersdorf.com
www.prd.biophysics.beiersdorf.com
micro-test.beiersdorf.com
px1-us.vx.beiersdorf.com
azext-asia.beiersdorf.com
tsgw.beiersdorf.com
support-u22.beiersdorf.com
pressportal-no.beiersdorf.com
cms.microsites.beiersdorf.com
almere.beiersdorf.com
www.annualreport2012.beiersdorf.com
pim-mam-userguide.beiersdorf.com
interimreport2014-q3.beiersdorf.com
bdf-ias-deletion.beiersdorf.com
nso.beiersdorf.com
nvs.beiersdorf.com
www.vx.beiersdorf.com
www2.beiersdorf.com
images1.products.beiersdorf.com
az-support-bitbucket.beiersdorf.com
webconf01.beiersdorf.com
qa-presseportal-fi.beiersdorf.com
draft.beiersdorf.com
mbluenet-bmb.beiersdorf.com
dev.campusexperience.beiersdorf.com
az-support-confluence.beiersdorf.com
sftp.beiersdorf.com
hello.cewa.beiersdorf.com
bss.beiersdorf.com
www.interimreport2014-q2.beiersdorf.com
www.annualreport2007.beiersdorf.com
www.annualreport2016.beiersdorf.com
view.medical.beiersdorf.com
test-jira.beiersdorf.com
support.beiersdorf.com
sustainability.beiersdorf.com
lync15ws.beiersdorf.com
pre-mediaxplan.beiersdorf.com
interimreport2016-q2.beiersdorf.com
bitbucket.support.beiersdorf.com
px1-ap.vx.beiersdorf.com
20.beiersdorf.com
pearlfinder.beiersdorf.com
mail.support.beiersdorf.com
pressportal-dk.beiersdorf.com
bitbucket.support-test.beiersdorf.com
crosscompany-tchibo.beiersdorf.com
dam-q-eventhub.beiersdorf.com
nhc.beiersdorf.com
www.annualreport2011.beiersdorf.com
www.annualreport2009.beiersdorf.com
homeoffice.beiersdorf.com
503errorpage.beiersdorf.com
azext-devops-backup.beiersdorf.com
qa-micro-crosscompany-tchibo.beiersdorf.com
qa-oscar-and-paul-battleweeks.beiersdorf.com
ucpool09ws.beiersdorf.com
hautstudie.beiersdorf.com
dam-d-proc.beiersdorf.com
dam-api.beiersdorf.com
px1-eu.vx.beiersdorf.com
dam-d-uaa.beiersdorf.com
api.crm-prod.beiersdorf.com
pre.study-center.beiersdorf.com
mam-userguide.beiersdorf.com
login-www-nivea-com-br.beiersdorf.com
support-new.beiersdorf.com
cms.beiersdorf.com
api.shop-dev.beiersdorf.com
login-www-nordstoff-com.beiersdorf.com
micro-reference.beiersdorf.com
video.beiersdorf.com
annualreport2007.beiersdorf.com
az-temp-lx-backend.beiersdorf.com
marketplace-qa.beiersdorf.com
cms10uat-cd.beiersdorf.com
www.eucerin.beiersdorf.com
azext-devops.beiersdorf.com
micro-crosscompany-tchibo-prelive.beiersdorf.com
lync02ws.beiersdorf.com
click.medical.beiersdorf.com
www.ad-gallery.beiersdorf.com
gr.beiersdorf.com
sip.video.beiersdorf.com
mad.beiersdorf.com
devops.beiersdorf.com
annualreport2012.beiersdorf.com
www.hello.beiersdorf.com
micro-mam-userguide-prelive.beiersdorf.com
dermo-reference.beiersdorf.com
qa.socialwall.beiersdorf.com
az-uat-ste-frontdoor.beiersdorf.com
countrymaster.mobile.beiersdorf.com
mam-admin-q.beiersdorf.com
mediaxplan.beiersdorf.com
gbc.beiersdorf.com
dennis-g.sf-dev.beiersdorf.com
www.interimreport2016-q2.beiersdorf.com
search.beiersdorf.com
micro-pim-mam-userguide-prelive.beiersdorf.com
uat-pl.beiersdorf.com
payment-fat.beiersdorf.com
micro-pim-userguide-prelive.beiersdorf.com
cms10qa-socialwall.beiersdorf.com
qa.beiersdorf.com
fat-care-os.beiersdorf.com
qa-micro-userguide.beiersdorf.com
www.annualreport.beiersdorf.com
prd.biophysics.beiersdorf.com
interimreport2014-q1.beiersdorf.com
webconf05.beiersdorf.com
pim2-userguide.beiersdorf.com
annualreport2018.beiersdorf.com
c.beiersdorf.com
www.reports.beiersdorf.com
azext-op-u22.beiersdorf.com
lync11ws.beiersdorf.com
tst.biophysics.beiersdorf.com
api.shop-qual.beiersdorf.com
presseportal-no.beiersdorf.com
qa-micro-reference.beiersdorf.com
return500.beiersdorf.com
wvd.beiersdorf.com
shop-dev.beiersdorf.com
products.beiersdorf.com
azext-eu.beiersdorf.com
api.crm-qual.beiersdorf.com
mam-fnc-q.beiersdorf.com
dam-q-proc.beiersdorf.com
dam-d.beiersdorf.com
annualreport.beiersdorf.com
webconf04.beiersdorf.com
www.mobile.beiersdorf.com
www.ebm.beiersdorf.com
debug.acios.beiersdorf.com
wwwold.beiersdorf.com
oscar-and-paul-battleweeks-prelive.beiersdorf.com
micro-presseportal-fi-prelive.beiersdorf.com
marketplace.beiersdorf.com
annualreport2016.beiersdorf.com
pexip-teamsconn-eu.teams.beiersdorf.com
sf.beiersdorf.com
businesscards.beiersdorf.com
gsa.beiersdorf.com
bnc3.beiersdorf.com
mam-abo-d.beiersdorf.com
mam-abo-q.beiersdorf.com
mam-abo.beiersdorf.com
qa-pim1-userguide.beiersdorf.com
www.interimreport2015-q2.beiersdorf.com
www.annualreport2018.beiersdorf.com
www.showroom.beiersdorf.com
api.shop-prod.beiersdorf.com
dam-d-api.beiersdorf.com
dialin.beiersdorf.com
shop.beiersdorf.com
pages.n.beiersdorf.com
mad-az.beiersdorf.com
lync01ws.beiersdorf.com
confluence.support-test.beiersdorf.com
micro-designmanual-prelive.beiersdorf.com
webmail.systemmails.beiersdorf.com
passwordreset.beiersdorf.com
az-uat-euc-frontdoor.beiersdorf.com
azext-eu-sbs-u22.beiersdorf.com
lync03ws.beiersdorf.com
bimi.beiersdorf.com
study-center.beiersdorf.com
ham-vbp-e.beiersdorf.com
login-uat-nivea-de.beiersdorf.com
cloud.n.beiersdorf.com
nbc.beiersdorf.com
annualreport2013.beiersdorf.com
www.annualreport2015.beiersdorf.com
www.pearlfinder.beiersdorf.com
uat.beiersdorf.com
tsgw-test.beiersdorf.com
www.trademarketing.beiersdorf.com
systemmails.beiersdorf.com
webconf02.beiersdorf.com
azext-us-u22.beiersdorf.com
azext-eu-side-by-side.beiersdorf.com
confluence.support-u22.beiersdorf.com
lync07ws.beiersdorf.com
jira.support.beiersdorf.com
dev.campus-experience.beiersdorf.com
login-uat-nivea-com-br.beiersdorf.com
api.swagger-prod.beiersdorf.com
ext.beiersdorf.com
nbt.beiersdorf.com
qa-presseportal-no.beiersdorf.com
interimreport2018-q2.beiersdorf.com
uat-pt-br.beiersdorf.com
uat-th.beiersdorf.com
qa-pim-mam-userguide.beiersdorf.com
smpl.beiersdorf.com
dam-d-eventhub.beiersdorf.com
direc02ws.beiersdorf.com
campus-experience.beiersdorf.com
trusted-pearlfinders.beiersdorf.com
azext-eu-side-by-side-22.beiersdorf.com
ndo.beiersdorf.com
api.swagger-dev.beiersdorf.com
gtm.beiersdorf.com
bluebay.beiersdorf.com
qa-pim-userguide.beiersdorf.com
micro-presseportal-se-prelive.beiersdorf.com
interimreport2015-q2.beiersdorf.com
annualreport2005.beiersdorf.com
securedrive.beiersdorf.com
mail.essentials.beiersdorf.com
interimreport2019-q2.beiersdorf.com
userguide.beiersdorf.com
qa-presseportal-dk.beiersdorf.com
careers.beiersdorf.com
dev.biophysics.beiersdorf.com
bnc3.emails.beiersdorf.com
phc.beiersdorf.com
eop.beiersdorf.com
mail.support-backup.beiersdorf.com
micro-cms.beiersdorf.com
mam-admin-d.beiersdorf.com
sftp-test.beiersdorf.com
api.crm-dev.beiersdorf.com
dam.beiersdorf.com
campusexperience.beiersdorf.com
pressportal-fi.beiersdorf.com
qa-micro-demo.beiersdorf.com
dam-q-uaa.beiersdorf.com
dam-q.beiersdorf.com
annualreport2015.beiersdorf.com
relaunch.beiersdorf.com
interimreport2014-q2.beiersdorf.com
pim-userguide.beiersdorf.com
annualreport2014.beiersdorf.com
sfc-test.beiersdorf.com
uat-care-os.beiersdorf.com
cloud.medical.beiersdorf.com
selector1._domainkey.beiersdorf.com
admin-acios.beiersdorf.com
azext-eu-redir.beiersdorf.com
financials.beiersdorf.com
}


def get_ip_by_domains sites
  result = []
  sites.each_slice(20) do |sites_in_20|

    threads = []
    sites_in_20.each do |site|
      threads << Thread.new do
        puts "site: #{site}"
        server = Server.where("name = ?", site).first
        if server.blank?
          server = Server.create name: site, comment: 'beiersdorf.com'
        end

        command = "dig +short #{site}"
        dig_result = `#{command}`

        Rails.logger.info "== command: #{command}, result: #{dig_result}"

        server.dig_result = dig_result
        server.save!
      end
    end
    threads.each {|t| t.join}

    sleep 5
  end
end

def get_wafw00f_result_by_domains sites
  sites.each_slice(20) do |sites_in_20|

    threads = []
    sites_in_20.each do |site|
      threads << Thread.new do
        puts "site: #{site}, index: #{sites.index(site)}"
        server = Server.where("name = ?", site).first
        if server.blank?
          server = Server.create name: site
        end

        command = "wafw00f #{site}"
        result = `#{command}`
        Rails.logger.info "== command: #{command}, result: #{result}"

        server.wafwoof_result = result
        server.save!
      end
    end
  end
end

get_ip_by_domains sites
#get_wafw00f_result_by_domains sites
